baseURL = "https://ooni.org"
languageCode = "en-us"
title = "OONI: Open Observatory of Network Interference"
DefaultContentLanguage = "en"
pluralizeListTitles = false

[params]
description = "Open Observatory of Network Interference (OONI). A free software, global observation network for detecting censorship, surveillance and traffic manipulation on the internet"

[Languages]
[Languages.ar]
[Languages.en]
[Languages.es]
[Languages.ca]
[Languages.fr]
[Languages.pt]
[Languages.zh]

[outputFormats]
[outputFormats.PageIndex]
mediaType = "application/json"
baseName = "pageindex"
isPlainText = true
notAlternative = true

[outputs]
  home = ["HTML", "PageIndex", "RSS"]
