---
jobs:
  deploy-to-gh:
    docker:
      - image: cibuilds/base
    working_directory: /workspace
    steps:
      - attach_workspace:
          at: /workspace
      - add_ssh_keys:
          fingerprints:
            - "e7:10:10:55:33:cb:dd:cd:35:87:50:81:4e:8f:31:56"
      - run: ./scripts/deploy_circleci.sh
  build-website:
    docker:
      - image: cibuilds/base
    working_directory: ~/hugo
    steps:
      - hugo/install:
          version: '0.58.2'
      - checkout
      - run: ./scripts/build_website.sh
      - persist_to_workspace:
          root: ~/hugo
          paths:
            - public
            - scripts
orbs:
  hugo: circleci/hugo@0.2
version: 2.1
workflows:
  main:
    jobs:
      - build-website
      - deploy-to-gh:
          filters:
              branches:
                only: master
          requires:
            - build-website
